CREATE TABLE [dbo].[Notices]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[ParentId] INT NULL,
	[ParentKey] NVARCHAR(255) NULL,

	[Name] NVARCHAR(100) NOT NULL,
	[Title] NVARCHAR(255) NULL,
	[Content] NVARCHAR(MAX) NULL,

	[IsPinned] BIT NULL DEFAULT(0),

	[CreatedBy] NVARCHAR(255) NULL,
	[Created] DATETIME2 DEFAULT(GETDATE()) NULL,
	[ModifiedBy] NVARCHAR(255) NULL,
	[Modified] DATETIME2 NULL,

	[ReadCount] INT DEFAULT 0,

	[FileName] NVARCHAR(255) NULL,
	[FileSize] INT DEFAULT 0,
	[DownCount] INT DEFAULT 0,

	[Ref] INT NOT NULL,
	[Step] INT DEFAULT 0,
	[RefOrder] INT DEFAULT 0
)
GO
